# Generated by Django 2.2.4 on 2020-08-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('price_per_unit', models.TextField(blank=True, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_7', models.ImageField(blank=True, null=True, upload_to='')),
                ('area', models.TextField(blank=True, null=True)),
                ('rooms', models.TextField(blank=True, null=True)),
                ('bedrooms', models.TextField(blank=True, null=True)),
                ('bathrooms', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('building_age', models.TextField(blank=True, null=True)),
                ('parking', models.TextField(blank=True, null=True)),
                ('cooling', models.TextField(blank=True, null=True)),
                ('heating', models.TextField(blank=True, null=True)),
                ('sewer', models.CharField(blank=True, choices=[('Public', 'Public'), ('City', 'City')], max_length=100, null=True)),
                ('water', models.CharField(blank=True, choices=[('Public', 'Public'), ('City', 'City')], max_length=100, null=True)),
                ('exercise_room', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True)),
                ('storage_room', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True)),
                ('first_floor', models.ImageField(blank=True, null=True, upload_to='')),
                ('first_floor_description', models.TextField(blank=True, null=True)),
                ('second_floor', models.ImageField(blank=True, null=True, upload_to='')),
                ('second_floor_description', models.TextField(blank=True, null=True)),
                ('third_floor', models.ImageField(blank=True, null=True, upload_to='')),
                ('third_floor_description', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
