# Generated by Django 2.2.4 on 2020-08-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_property_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='2'),
            preserve_default=False,
        ),
    ]
