# Generated by Django 2.2.4 on 2020-08-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summmary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
