# Generated by Django 2.2.4 on 2020-08-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_property_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
