# Generated by Django 2.2.4 on 2020-08-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20200821_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='creator',
            field=models.TextField(blank=True, null=True),
        ),
    ]
