# Generated by Django 2.2.4 on 2020-08-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20200822_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agency',
            field=models.TextField(blank=True, null=True),
        ),
    ]
