# Generated by Django 2.2.4 on 2020-08-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_tour_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
