# Generated by Django 2.2.4 on 2020-08-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_tour_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
