# Generated by Django 2.2.4 on 2020-08-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_article_author_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
