# Generated by Django 2.2.4 on 2020-08-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_article_author_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('blog', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
