# Generated by Django 2.2.4 on 2020-08-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agency',
            field=models.TextField(default='Gold Man Scchs'),
            preserve_default=False,
        ),
    ]
