# Generated by Django 2.2.4 on 2020-08-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_auto_20200827_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
