# Generated by Django 2.2.4 on 2020-08-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trials',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
