# Generated by Django 2.2.4 on 2020-09-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_valuation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='developer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
