# Generated by Django 2.2.4 on 2020-09-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_boost'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boost',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boost',
            name='sale_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
