# Generated by Django 2.2.4 on 2020-09-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0041_auto_20200902_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boost',
            name='area',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boost',
            name='bathrooms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boost',
            name='bedrooms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boost',
            name='rooms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
