# Generated by Django 2.2.4 on 2020-09-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0043_auto_20200902_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
