# Generated by Django 2.2.4 on 2020-09-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0046_auto_20200902_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
