# Generated by Django 2.2.4 on 2020-09-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0047_auto_20200902_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='boost',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
