# Generated by Django 2.2.4 on 2020-09-02 22:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0049_boost_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='expire',
            field=models.DateField(default=datetime.datetime(2020, 9, 2, 22, 54, 28, 284586, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
