# Generated by Django 2.2.4 on 2020-09-12 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0052_newletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newletter',
            new_name='Newsletter',
        ),
    ]
